title: Haochen Miao # your name (or website title) here
logo: "/images/linkedin.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with 2+ years of experience in data analytics, and a bachelor's degree in Data Science from University of Washington Seattle.
  <br><br>
  Dean's List (2021- 2023)
  <br><br>
  <a href="https://www.linkedin.com/in/haochen-miao-250166196/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
